export const STORIES_REQUEST = 'STORIES_REQUEST'
export const STORIES_COMPLETE = 'STORIES_COMPLETE'
export const STORIES_FAIL = 'STORIES_FAIL'

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST'
export const COMMENTS_COMPLETE = 'COMMENTS_COMPLETE'
export const COMMENTS_FAIL = 'COMMENTS_FAIL'

export const TOGGLE_SUB_COMMENTS = 'TOGGLE_SUB_COMMENTS'
